version: '3'
services:
  nginx:
    image: "nginx:1.13"
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - "./config/nginx/conf.d:/etc/nginx/conf.d:ro"
     - "./certs:/etc/nginx/certs:ro"
  api-seeder:
    image: "btcz/bitcoinz-api-seeder"
